--- # PLAYBOOK FOR HAWKEYE vRAD
- name: vRAD 
  hosts: 106_vGUI
  remote_user: ubuntu
  become: yes
  vars:
    script_file_path: /home/ubuntu/script.sh
    script_content: |
          #!/bin/bash
          mkdir /dev/shm/radacct
          touch /dev/shm/radacct/detail-$(date +"%Y-%m-%d")-log
          chmod 777 /dev/shm/radacct -R
          cp /dev/shm/radacct/detail-$(date +"%Y-%m-%d")-log /dev/shm/radacct/detail-$(date +"%Y-%m-%d_%H-%M-%S")_1
          echo " " > /dev/shm/radacct/detail-$(date +"%Y-%m-%d")-log
          rm -f /dev/shm/radacct/detail-$(date --date="yesterday" +"%Y-%m-%d")-log
          find /dev/shm/radacct/* -mmin +5 -exec rm {} \;
  tasks:
   - name: Create script file
     file:
       path: "{{ script_file_path }}"
       state: touch
   - name: Add content to script file
     lineinfile:
       path: "{{ script_file_path }}"
       line: "{{ item }}"
       state: present
     with_items: "{{ script_content.split('\n') }}
