--- # PLAYBOOK FOR HAWKEYE DPI NODE
- name: DPI Node Mandatory CMDs
  hosts: all
  remote_user: ubuntu
  become: yes
  pre_tasks:
      ### Check OS Version and Host Type ####
    - name: Gather host facts
      setup:
    - name: Check OS version and Host_type
      debug:
         msg: 
           - "OS version is {{ ansible_distribution_version }} and Host type is {{ ansible_virtualization_role }}"
    - name: Terminate playbook
      meta: end_play
      when: ansible_distribution_version != '22.10' or ansible_virtualization_role != 'guest'
  tasks:
       ####### Add ppa repository #######    
    - name: Add Repository
      ansible.builtin.apt_repository: 
        validate_certs: no
        repo: "ppa:deadsnakes/ppa"
        state: present
      when: inventory_hostname in groups["102_vDPI"]

       ###### Install libraries #########
    - name: Install Libraries
      apt:
        update_cache: yes
        pkg: 
          - "build-essential"
          - "libmysqlclient-dev"
          - "libbpf-dev"
          - "python3"
          - "python3-dev"
          - "python3-tweepy"
          - "gcc-multilib"
          - "libpcap-dev"
          - "libboost-dev"
          - "cmake"
          - "clang"
          - "libbpf-dev"
          - "make"
          - "libgtest-dev"
          - "libgmock-dev"
        state: present
      when: inventory_hostname in groups["102_vDPI"]

  ##### python3.9 packages are required according to provided document #####
  ##### got this error while installing python3.9 //Unable to locate package python3.9 #####

