- name: Install Git
  hosts: all
  remote_user: ubuntu
  become: yes  
  tasks:
  - name: Check if Git is already installed
    stat:
      path: /home/ansible
    register: git_installed
  
  - name: Install Git
    when: git_installed.stat.exists == False
    package:
      name: git
      state: present

