- name: Install Apache
  hosts: all
  remote_user: ubuntu
  become_user: root
  become: yes
  vars:
    httpd_package: apache2
  tasks:
  - name: Check if Apache is already installed
    stat:
      path: /home/ansible
    register: apache_installed
  
  - name: Install Apache
    when: apache_installed.stat.exists == False
    apt:
      name: "{{ httpd_package }}"
      state: present
  - name: Start Apache service
    service:
      name: apache2
      state: started
    when: apache_installed.stat.exists == True

